# Generated by Django 5.2 on 2025-04-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='configaudit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='configcontrol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lru',
            options={},
        ),
        migrations.AlterModelOptions(
            name='malfunction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='permit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sort',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uav',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uavbalancecontrol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uavversions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uavweightscontrol',
            options={},
        ),
    ]
